class PopulateSpreeCurrencies < ActiveRecord::Migration
  ITEMS = [
      { :country_id => '3', :country_name => 'Afghanistan', :country_iso => 'AF', :name => 'Afghan Afghani', :code => 'AFN', :symbol => '؋', :symbol_position => 'before' },
      { :country_id => '6', :country_name => 'Albania', :country_iso => 'AL', :name => 'Albanian Lek', :code => 'ALL', :symbol => 'Lek', :symbol_position => 'before' },
      { :country_id => '62', :country_name => 'Algeria', :country_iso => 'DZ', :name => 'Algerian Dinar', :code => 'DZD', :symbol => 'د.ج', :symbol_position => 'before' },
      { :country_id => '11', :country_name => 'American Samoa', :country_iso => 'AS', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '1', :country_name => 'Andorra', :country_iso => 'AD', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '8', :country_name => 'Angola', :country_iso => 'AO', :name => 'Angolan Kwanza', :code => 'AOA', :symbol => 'Kz', :symbol_position => 'before' },
      { :country_id => '5', :country_name => 'Anguilla', :country_iso => 'AI', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      # { :country_id => '9', :country_name => 'Antarctica', :country_iso => 'AQ', :name => '', :code => '', :symbol => '' },
      { :country_id => '4', :country_name => 'Antigua and Barbuda', :country_iso => 'AG', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '10', :country_name => 'Argentina', :country_iso => 'AR', :name => 'Argentine Peso', :code => 'ARS', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '7', :country_name => 'Armenia', :country_iso => 'AM', :name => 'Armenian Dram', :code => 'AMD', :symbol => '', :symbol_position => 'before' },
      { :country_id => '14', :country_name => 'Aruba', :country_iso => 'AW', :name => 'Aruban Guilder', :code => 'AWG', :symbol => 'ƒ', :symbol_position => 'before' },
      { :country_id => '13', :country_name => 'Australia', :country_iso => 'AU', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '12', :country_name => 'Austria', :country_iso => 'AT', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '16', :country_name => 'Azerbaijan', :country_iso => 'AZ', :name => 'Azerbaijani Manat', :code => 'AZN', :symbol => 'ман', :symbol_position => 'before' },
      { :country_id => '32', :country_name => 'Bahamas', :country_iso => 'BS', :name => 'Bahamian Dollar', :code => 'BSD', :symbol => 'B$', :symbol_position => 'before' },
      { :country_id => '23', :country_name => 'Bahrain', :country_iso => 'BH', :name => 'Bahraini Dinar', :code => 'BHD', :symbol => '.د.ب', :symbol_position => 'before' },
      { :country_id => '19', :country_name => 'Bangladesh', :country_iso => 'BD', :name => 'Bangladeshi Taka', :code => 'BDT', :symbol => '৳', :symbol_position => 'before' },
      { :country_id => '18', :country_name => 'Barbados', :country_iso => 'BB', :name => 'Barbados Dollar', :code => 'BBD', :symbol => 'Bds$', :symbol_position => 'before' },
      { :country_id => '36', :country_name => 'Belarus', :country_iso => 'BY', :name => 'Belarussian Ruble', :code => 'BYR', :symbol => 'Br', :symbol_position => 'before' },
      { :country_id => '20', :country_name => 'Belgium', :country_iso => 'BE', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '37', :country_name => 'Belize', :country_iso => 'BZ', :name => 'Belize Dollar', :code => 'BZD', :symbol => 'BZ$', :symbol_position => 'before' },
      { :country_id => '25', :country_name => 'Benin', :country_iso => 'BJ', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '27', :country_name => 'Bermuda', :country_iso => 'BM', :name => 'Bermudian Dollar', :code => 'BMD', :symbol => 'BD$', :symbol_position => 'before' },
      { :country_id => '33', :country_name => 'Bhutan', :country_iso => 'BT', :name => 'Bhutanese Ngultrum', :code => 'BTN', :symbol => 'Nu.', :symbol_position => 'before' },
      { :country_id => '29', :country_name => "Bolivia, Plurinational State of", :country_iso => 'BO', :name => 'Bolivian Boliviano', :code => 'BOB', :symbol => 'Bs.', :symbol_position => 'before' },
      { :country_id => '30', :country_name => "Bonaire, Sint Eustatius and Saba", :country_iso => 'BQ', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '17', :country_name => 'Bosnia and Herzegovina', :country_iso => 'BA', :name => 'Bosnia and Herzegovina Convertible Mark', :code => 'BAM', :symbol => 'KM', :symbol_position => 'before' },
      { :country_id => '35', :country_name => 'Botswana', :country_iso => 'BW', :name => 'Botswanan Pula', :code => 'BWP', :symbol => 'P', :symbol_position => 'before' },
      { :country_id => '34', :country_name => 'Bouvet Island', :country_iso => 'BV', :name => 'Norwegian Krone', :code => 'NOK', :symbol => 'kr', :symbol_position => 'before' },
      { :country_id => '31', :country_name => 'Brazil', :country_iso => 'BR', :name => 'Brazilian Real', :code => 'BRL', :symbol => 'R$', :symbol_position => 'before' },
      { :country_id => '106', :country_name => 'British Indian Ocean Territory', :country_iso => 'IO', :name => 'Pound Sterling', :code => 'GBP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '28', :country_name => 'Brunei Darussalam', :country_iso => 'BN', :name => 'Brunei Dollar', :code => 'BND', :symbol => 'B$', :symbol_position => 'before' },
      { :country_id => '22', :country_name => 'Bulgaria', :country_iso => 'BG', :name => 'Bulgarian Lev', :code => 'BGN', :symbol => 'лв.', :symbol_position => 'before' },
      { :country_id => '21', :country_name => 'Burkina Faso', :country_iso => 'BF', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '24', :country_name => 'Burundi', :country_iso => 'BI', :name => 'Burundi Franc', :code => 'BIF', :symbol => 'FBu', :symbol_position => 'before' },
      { :country_id => '117', :country_name => 'Cambodia', :country_iso => 'KH', :name => 'Cambodian Riel', :code => 'KHR', :symbol => '៛', :symbol_position => 'before' },
      { :country_id => '47', :country_name => 'Cameroon', :country_iso => 'CM', :name => 'Central African CFA Franc', :code => 'XAF', :symbol => 'FCFA', :symbol_position => 'before' },
      { :country_id => '38', :country_name => 'Canada', :country_iso => 'CA', :name => 'Canadian Dollar', :code => 'CAD', :symbol => 'C$', :symbol_position => 'before' },
      { :country_id => '52', :country_name => 'Cape Verde', :country_iso => 'CV', :name => 'Cape Verde Escudo', :code => 'CVE', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '124', :country_name => 'Cayman Islands', :country_iso => 'KY', :name => 'Cayman Islands Dollar', :code => 'KYD', :symbol => 'CI$', :symbol_position => 'before' },
      { :country_id => '41', :country_name => 'Central African Republic', :country_iso => 'CF', :name => 'Central African CFA Franc', :code => 'XAF', :symbol => 'FCFA', :symbol_position => 'before' },
      { :country_id => '214', :country_name => 'Chad', :country_iso => 'TD', :name => 'Central African CFA Franc', :code => 'XAF', :symbol => 'FCFA', :symbol_position => 'before' },
      { :country_id => '46', :country_name => 'Chile', :country_iso => 'CL', :name => 'Chilean Peso', :code => 'CLP', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '48', :country_name => 'China', :country_iso => 'CN', :name => 'Yuan Renminbi', :code => 'CNY', :symbol => '¥', :symbol_position => 'before' },
      { :country_id => '54', :country_name => 'Christmas Island', :country_iso => 'CX', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '39', :country_name => 'Cocos (Keeling) Islands', :country_iso => 'CC', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '49', :country_name => 'Colombia', :country_iso => 'CO', :name => 'Colombian Peso', :code => 'COP', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '119', :country_name => 'Comoros', :country_iso => 'KM', :name => 'Comoro Franc', :code => 'KMF', :symbol => 'CF', :symbol_position => 'before' },
      { :country_id => '42', :country_name => 'Congo', :country_iso => 'CG', :name => 'Central African CFA Franc', :code => 'XAF', :symbol => 'FCFA', :symbol_position => 'before' },
      { :country_id => '40', :country_name => "Congo, The Democratic Republic of the", :country_iso => 'CD', :name => 'Congolese Franc', :code => 'CDF', :symbol => 'FC', :symbol_position => 'before' },
      { :country_id => '45', :country_name => 'Cook Islands', :country_iso => 'CK', :name => 'New Zealand Dollar', :code => 'NZD', :symbol => 'NZ$', :symbol_position => 'before' },
      { :country_id => '50', :country_name => 'Costa Rica', :country_iso => 'CR', :name => 'Costa Rican Colón', :code => 'CRC', :symbol => '₡', :symbol_position => 'before' },
      { :country_id => '98', :country_name => 'Croatia', :country_iso => 'HR', :name => 'Croatian Kuna', :code => 'HRK', :symbol => 'kn', :symbol_position => 'before' },
      { :country_id => '51', :country_name => 'Cuba', :country_iso => 'CU', :name => 'Cuban Peso Convertible', :code => 'CUC', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '53', :country_name => 'Curaçao', :country_iso => 'CW', :name => 'Netherlands Antillean Guilder', :code => 'ANG', :symbol => 'NAƒ', :symbol_position => 'before' },
      { :country_id => '55', :country_name => 'Cyprus', :country_iso => 'CY', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '56', :country_name => 'Czech Republic', :country_iso => 'CZ', :name => 'Czech Koruna', :code => 'CZK', :symbol => 'Kč', :symbol_position => 'before' },
      { :country_id => '44', :country_name => "Côte d'Ivoire", :country_iso => 'CI', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '59', :country_name => 'Denmark', :country_iso => 'DK', :name => 'Danish Krone', :code => 'DKK', :symbol => 'kr.', :symbol_position => 'before' },
      { :country_id => '58', :country_name => 'Djibouti', :country_iso => 'DJ', :name => 'Djibouti Franc', :code => 'DJF', :symbol => 'Fdj', :symbol_position => 'before' },
      { :country_id => '60', :country_name => 'Dominica', :country_iso => 'DM', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '61', :country_name => 'Dominican Republic', :country_iso => 'DO', :name => 'Dominican Peso', :code => 'DOP', :symbol => 'RD$', :symbol_position => 'before' },
      { :country_id => '63', :country_name => 'Ecuador', :country_iso => 'EC', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '65', :country_name => 'Egypt', :country_iso => 'EG', :name => 'Egyptian Pound', :code => 'EGP', :symbol => 'E£', :symbol_position => 'before' },
      { :country_id => '209', :country_name => 'El Salvador', :country_iso => 'SV', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '88', :country_name => 'Equatorial Guinea', :country_iso => 'GQ', :name => 'Central African CFA Franc', :code => 'XAF', :symbol => 'FCFA', :symbol_position => 'before' },
      { :country_id => '67', :country_name => 'Eritrea', :country_iso => 'ER', :name => 'Eritrean Nakfa', :code => 'ERN', :symbol => 'Nfk', :symbol_position => 'before' },
      { :country_id => '64', :country_name => 'Estonia', :country_iso => 'EE', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '69', :country_name => 'Ethiopia', :country_iso => 'ET', :name => 'Ethiopian Birr', :code => 'ETB', :symbol => 'Br', :symbol_position => 'before' },
      { :country_id => '72', :country_name => 'Falkland Islands (Malvinas)', :country_iso => 'FK', :name => 'Falkland Islands Pound', :code => 'FKP', :symbol => 'FK£', :symbol_position => 'before' },
      { :country_id => '74', :country_name => 'Faroe Islands', :country_iso => 'FO', :name => 'Danish Krone', :code => 'DKK', :symbol => 'kr.', :symbol_position => 'before' },
      { :country_id => '71', :country_name => 'Fiji', :country_iso => 'FJ', :name => 'Fiji Dollar', :code => 'FJD', :symbol => 'FJ$', :symbol_position => 'before' },
      { :country_id => '70', :country_name => 'Finland', :country_iso => 'FI', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '75', :country_name => 'France', :country_iso => 'FR', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '80', :country_name => 'French Guiana', :country_iso => 'GF', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '175', :country_name => 'French Polynesia', :country_iso => 'PF', :name => 'CFP Franc', :code => 'XPF', :symbol => 'F', :symbol_position => 'before' },
      #{ :country_id => '215', :country_name => 'French Southern Territories', :country_iso => 'TF', :name => '', :code => '', :symbol => '' },
      { :country_id => '76', :country_name => 'Gabon', :country_iso => 'GA', :name => 'Central African CFA Franc', :code => 'XAF', :symbol => 'FCFA', :symbol_position => 'before' },
      { :country_id => '85', :country_name => 'Gambia', :country_iso => 'GM', :name => 'Gambian Dalasi', :code => 'GMD', :symbol => 'D', :symbol_position => 'before' },
      { :country_id => '79', :country_name => 'Georgia', :country_iso => 'GE', :name => 'Georgian Lari', :code => 'GEL', :symbol => '', :symbol_position => 'before' },
      { :country_id => '57', :country_name => 'Germany', :country_iso => 'DE', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '82', :country_name => 'Ghana', :country_iso => 'GH', :name => 'Ghana Cedi', :code => 'GHS', :symbol => 'GH₵', :symbol_position => 'before' },
      { :country_id => '83', :country_name => 'Gibraltar', :country_iso => 'GI', :name => 'Gibraltar Pound', :code => 'GIP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '89', :country_name => 'Greece', :country_iso => 'GR', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '84', :country_name => 'Greenland', :country_iso => 'GL', :name => 'Danish Krone', :code => 'DKK', :symbol => 'kr.', :symbol_position => 'before' },
      { :country_id => '78', :country_name => 'Grenada', :country_iso => 'GD', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '87', :country_name => 'Guadeloupe', :country_iso => 'GP', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '92', :country_name => 'Guam', :country_iso => 'GU', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '91', :country_name => 'Guatemala', :country_iso => 'GT', :name => 'Guatamalan Quetzal', :code => 'GTQ', :symbol => 'Q', :symbol_position => 'before' },
      { :country_id => '81', :country_name => 'Guernsey', :country_iso => 'GG', :name => 'Guernsey Pound', :code => 'GGP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '86', :country_name => 'Guinea', :country_iso => 'GN', :name => 'Guinea Franc', :code => 'GNF', :symbol => 'FG', :symbol_position => 'before' },
      { :country_id => '93', :country_name => 'Guinea-Bissau', :country_iso => 'GW', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '94', :country_name => 'Guyana', :country_iso => 'GY', :name => 'Guyana Dollar', :code => 'GYD', :symbol => 'G$', :symbol_position => 'before' },
      { :country_id => '99', :country_name => 'Haiti', :country_iso => 'HT', :name => 'Haitian Gourde', :code => 'HTG', :symbol => 'G', :symbol_position => 'before' },
      { :country_id => '96', :country_name => 'Heard Island and McDonald Islands', :country_iso => 'HM', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '235', :country_name => 'Holy See (Vatican City State)', :country_iso => 'VA', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '97', :country_name => 'Honduras', :country_iso => 'HN', :name => 'Honduran Lempira', :code => 'HNL', :symbol => 'L', :symbol_position => 'before' },
      { :country_id => '95', :country_name => 'Hong Kong', :country_iso => 'HK', :name => 'Hong Kong Dollar', :code => 'HKD', :symbol => 'HK$', :symbol_position => 'before' },
      { :country_id => '100', :country_name => 'Hungary', :country_iso => 'HU', :name => 'Hungarian Forint', :code => 'HUF', :symbol => 'Ft', :symbol_position => 'before' },
      { :country_id => '109', :country_name => 'Iceland', :country_iso => 'IS', :name => 'Icelandic Króna', :code => 'ISK', :symbol => 'kr', :symbol_position => 'before' },
      { :country_id => '105', :country_name => 'India', :country_iso => 'IN', :name => 'Indian Rupee', :code => 'INR', :symbol => 'Rs', :symbol_position => 'before' },
      { :country_id => '101', :country_name => 'Indonesia', :country_iso => 'ID', :name => 'Indonesian Rupiah', :code => 'IDR', :symbol => 'Rp', :symbol_position => 'before' },
      { :country_id => '108', :country_name => "Iran, Islamic Republic of", :country_iso => 'IR', :name => 'Iranian Rial', :code => 'IRR', :symbol => '﷼', :symbol_position => 'before' },
      { :country_id => '107', :country_name => 'Iraq', :country_iso => 'IQ', :name => 'Iraqi Dinar', :code => 'IQD', :symbol => 'ع.د', :symbol_position => 'before' },
      { :country_id => '102', :country_name => 'Ireland', :country_iso => 'IE', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '104', :country_name => 'Isle of Man', :country_iso => 'IM', :name => 'Isle of Man Pound', :code => 'IMP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '103', :country_name => 'Israel', :country_iso => 'IL', :name => 'Israeli New Shekel', :code => 'ILS', :symbol => '	₪', :symbol_position => 'before' },
      { :country_id => '110', :country_name => 'Italy', :country_iso => 'IT', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '112', :country_name => 'Jamaica', :country_iso => 'JM', :name => 'Jamaican Dollar', :code => 'JMD', :symbol => 'J$', :symbol_position => 'before' },
      { :country_id => '114', :country_name => 'Japan', :country_iso => 'JP', :name => 'Japanese Yen', :code => '¥', :symbol => 'JPY', :symbol_position => 'before' },
      { :country_id => '111', :country_name => 'Jersey', :country_iso => 'JE', :name => 'Jersey Pound', :code => 'JEP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '113', :country_name => 'Jordan', :country_iso => 'JO', :name => 'Jordanian Dinar', :code => 'JOD', :symbol => '', :symbol_position => 'before' },
      { :country_id => '125', :country_name => 'Kazakhstan', :country_iso => 'KZ', :name => 'Kazakhstani Tenge', :code => 'KZT', :symbol => '₸', :symbol_position => 'before' },
      { :country_id => '115', :country_name => 'Kenya', :country_iso => 'KE', :name => 'Kenyan Shilling', :code => 'KES', :symbol => 'KSh', :symbol_position => 'before' },
      { :country_id => '118', :country_name => 'Kiribati', :country_iso => 'KI', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '121', :country_name => "Korea, Democratic People's Republic of", :country_iso => 'KP', :name => 'North Korean Won', :code => 'KPW', :symbol => '₩', :symbol_position => 'before' },
      { :country_id => '122', :country_name => "Korea, Republic of", :country_iso => 'KR', :name => 'South Korean Won', :code => 'KRW', :symbol => '₩', :symbol_position => 'before' },
      { :country_id => '123', :country_name => 'Kuwait', :country_iso => 'KW', :name => 'Kuwaiti Dinar', :code => 'KWD', :symbol => 'د.ك', :symbol_position => 'before' },
      { :country_id => '116', :country_name => 'Kyrgyzstan', :country_iso => 'KG', :name => 'Kyrgyzstani Som', :code => 'KGS', :symbol => '', :symbol_position => 'before' },
      { :country_id => '126', :country_name => "Lao People's Democratic Republic", :country_iso => 'LA', :name => 'Lao Kip', :code => 'LAK', :symbol => '₭', :symbol_position => 'before' },
      { :country_id => '135', :country_name => 'Latvia', :country_iso => 'LV', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '127', :country_name => 'Lebanon', :country_iso => 'LB', :name => 'Lebanese Pound', :code => 'LBP', :symbol => 'ل.ل', :symbol_position => 'before' },
      { :country_id => '132', :country_name => 'Lesotho', :country_iso => 'LS', :name => 'Lesotho Loti', :code => 'LSL', :symbol => 'M', :symbol_position => 'before' },
      { :country_id => '131', :country_name => 'Liberia', :country_iso => 'LR', :name => 'Liberian Dollar', :code => 'LRD', :symbol => 'L$', :symbol_position => 'before' },
      { :country_id => '136', :country_name => 'Libya', :country_iso => 'LY', :name => 'Libyan Dinar', :code => 'LYD', :symbol => 'LD', :symbol_position => 'before' },
      { :country_id => '129', :country_name => 'Liechtenstein', :country_iso => 'LI', :name => 'Swiss Franc', :code => 'CHF', :symbol => 'Fr.', :symbol_position => 'before' },
      { :country_id => '133', :country_name => 'Lithuania', :country_iso => 'LT', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '134', :country_name => 'Luxembourg', :country_iso => 'LU', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '148', :country_name => 'Macao', :country_iso => 'MO', :name => 'Macanese Pataca', :code => 'MOP', :symbol => 'MOP$', :symbol_position => 'before' },
      { :country_id => '144', :country_name => 'Macedonia, Republic of', :country_iso => 'MK', :name => 'Macedonian Denar', :code => 'MKD', :symbol => 'ден', :symbol_position => 'before' },
      { :country_id => '142', :country_name => 'Madagascar', :country_iso => 'MG', :name => 'Malagasy Ariary', :code => 'MGA', :symbol => 'Ar', :symbol_position => 'before' },
      { :country_id => '156', :country_name => 'Malawi', :country_iso => 'MW', :name => 'Malawian Kwacha', :code => 'MWK', :symbol => 'MK', :symbol_position => 'before' },
      { :country_id => '158', :country_name => 'Malaysia', :country_iso => 'MY', :name => 'Malaysian Ringgit', :code => 'MYR', :symbol => 'RM', :symbol_position => 'before' },
      { :country_id => '155', :country_name => 'Maldives', :country_iso => 'MV', :name => 'Maldivian Rufiyaa', :code => 'MVR', :symbol => 'Rf', :symbol_position => 'before' },
      { :country_id => '145', :country_name => 'Mali', :country_iso => 'ML', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '153', :country_name => 'Malta', :country_iso => 'MT', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '143', :country_name => 'Marshall Islands', :country_iso => 'MH', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '150', :country_name => 'Martinique', :country_iso => 'MQ', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '151', :country_name => 'Mauritania', :country_iso => 'MR', :name => 'Mauritanian Ouguiya', :code => 'MRO', :symbol => 'UM', :symbol_position => 'before' },
      { :country_id => '154', :country_name => 'Mauritius', :country_iso => 'MU', :name => 'Mauritian Rupee', :code => 'MUR', :symbol => '₨', :symbol_position => 'before' },
      { :country_id => '245', :country_name => 'Mayotte', :country_iso => 'YT', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '157', :country_name => 'Mexico', :country_iso => 'MX', :name => 'Mexican Peso', :code => 'MXN', :symbol => 'Mex$', :symbol_position => 'before' },
      { :country_id => '73', :country_name => 'Micronesia, Federated States of', :country_iso => 'FM', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '139', :country_name => 'Moldova, Republic of', :country_iso => 'MD', :name => 'Moldovan Leu', :code => 'MDL', :symbol => '', :symbol_position => 'before' },
      { :country_id => '138', :country_name => 'Monaco', :country_iso => 'MC', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '147', :country_name => 'Mongolia', :country_iso => 'MN', :name => 'Mongolian Tögrög', :code => 'MNT', :symbol => '₮', :symbol_position => 'before' },
      { :country_id => '140', :country_name => 'Montenegro', :country_iso => 'ME', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '152', :country_name => 'Montserrat', :country_iso => 'MS', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '137', :country_name => 'Morocco', :country_iso => 'MA', :name => 'Moroccan Dirham', :code => 'MAD', :symbol => 'MAD', :symbol_position => 'before' },
      { :country_id => '159', :country_name => 'Mozambique', :country_iso => 'MZ', :name => 'Mozambican Metical', :code => 'MZN', :symbol => 'MT', :symbol_position => 'before' },
      { :country_id => '146', :country_name => 'Myanmar', :country_iso => 'MM', :name => 'Myanmar Kyat', :code => 'MMK', :symbol => 'K', :symbol_position => 'before' },
      { :country_id => '160', :country_name => 'Namibia', :country_iso => 'NA', :name => 'Namibian Dollar', :code => 'NAD', :symbol => 'N$', :symbol_position => 'before' },
      { :country_id => '169', :country_name => 'Nauru', :country_iso => 'NR', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '168', :country_name => 'Nepal', :country_iso => 'NP', :name => 'Nepalese Rupee', :code => 'NPR', :symbol => 'Rs', :symbol_position => 'before' },
      { :country_id => '166', :country_name => 'Netherlands', :country_iso => 'NL', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '161', :country_name => 'New Caledonia', :country_iso => 'NC', :name => 'CFP Franc', :code => 'XPF', :symbol => 'F', :symbol_position => 'before' },
      { :country_id => '171', :country_name => 'New Zealand', :country_iso => 'NZ', :name => 'New Zealand Dollar', :code => 'NZD', :symbol => 'NZ$', :symbol_position => 'before' },
      { :country_id => '165', :country_name => 'Nicaragua', :country_iso => 'NI', :name => 'Córdoba', :code => 'NIO', :symbol => 'C$', :symbol_position => 'before' },
      { :country_id => '162', :country_name => 'Niger', :country_iso => 'NE', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '164', :country_name => 'Nigeria', :country_iso => 'NG', :name => 'Naira', :code => 'NGN', :symbol => '₦', :symbol_position => 'before' },
      { :country_id => '170', :country_name => 'Niue', :country_iso => 'NU', :name => 'New Zealand Dollar', :code => 'NZD', :symbol => 'NZ$', :symbol_position => 'before' },
      { :country_id => '163', :country_name => 'Norfolk Island', :country_iso => 'NF', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '149', :country_name => 'Northern Mariana Islands', :country_iso => 'MP', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '167', :country_name => 'Norway', :country_iso => 'NO', :name => 'Krone', :code => 'NOK', :symbol => 'kr', :symbol_position => 'before' },
      { :country_id => '172', :country_name => 'Oman', :country_iso => 'OM', :name => 'Omani Rial', :code => 'OMR', :symbol => 'ر.ع.', :symbol_position => 'before' },
      { :country_id => '178', :country_name => 'Pakistan', :country_iso => 'PK', :name => 'Pakistani Rupee', :code => 'PKR', :symbol => 'Rs', :symbol_position => 'before' },
      { :country_id => '184', :country_name => 'Palau', :country_iso => 'PW', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '182', :country_name => 'Palestine, State of', :country_iso => 'PS', :name => 'Israeli New Shekel', :code => 'ILS', :symbol => '	₪', :symbol_position => 'before' },
      { :country_id => '173', :country_name => 'Panama', :country_iso => 'PA', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '176', :country_name => 'Papua New Guinea', :country_iso => 'PG', :name => 'Papua New Guinean Kina', :code => 'PGK', :symbol => 'K', :symbol_position => 'before' },
      { :country_id => '185', :country_name => 'Paraguay', :country_iso => 'PY', :name => 'Paraguayan Guaraní', :code => 'PYG', :symbol => '₲', :symbol_position => 'before' },
      { :country_id => '174', :country_name => 'Peru', :country_iso => 'PE', :name => 'Peruvian Nuevo Sol', :code => 'PEN', :symbol => 'S/', :symbol_position => 'before' },
      { :country_id => '177', :country_name => 'Philippines', :country_iso => 'PH', :name => 'Philippine Peso', :code => 'PHP', :symbol => '	₱', :symbol_position => 'before' },
      { :country_id => '181', :country_name => 'Pitcairn', :country_iso => 'PN', :name => 'New Zealand Dollar', :code => 'NZD', :symbol => 'NZ$', :symbol_position => 'before' },
      { :country_id => '179', :country_name => 'Poland', :country_iso => 'PL', :name => 'Polish Złoty', :code => 'PLN', :symbol => 'zł', :symbol_position => 'before' },
      { :country_id => '183', :country_name => 'Portugal', :country_iso => 'PT', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '186', :country_name => 'Qatar', :country_iso => 'QA', :name => 'Qatari Riyal', :code => 'QAR', :symbol => 'ريال', :symbol_position => 'before' },
      { :country_id => '188', :country_name => 'Romania', :country_iso => 'RO', :name => 'Romanian Leu', :code => 'RON', :symbol => '', :symbol_position => 'before' },
      { :country_id => '190', :country_name => 'Russian Federation', :country_iso => 'RU', :name => 'Russian Ruble', :code => 'RUB', :symbol => '₽', :symbol_position => 'before' },
      { :country_id => '191', :country_name => 'Rwanda', :country_iso => 'RW', :name => 'Rwandan Franc', :code => 'RWF', :symbol => 'FRw', :symbol_position => 'before' },
      { :country_id => '187', :country_name => 'Réunion', :country_iso => 'RE', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '26', :country_name => 'Saint Barthélemy', :country_iso => 'BL', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '198', :country_name => 'Saint Helena, Ascension and Tristan da Cunha', :country_iso => 'SH', :name => 'Saint Helena Pound', :code => 'SHP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '120', :country_name => 'Saint Kitts and Nevis', :country_iso => 'KN', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '128', :country_name => 'Saint Lucia', :country_iso => 'LC', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '141', :country_name => 'Saint Martin (French part)', :country_iso => 'MF', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '180', :country_name => 'Saint Pierre and Miquelon', :country_iso => 'PM', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '236', :country_name => 'Saint Vincent and the Grenadines', :country_iso => 'VC', :name => 'East Caribbean Dollar', :code => 'XCD', :symbol => 'EC$', :symbol_position => 'before' },
      { :country_id => '243', :country_name => 'Samoa', :country_iso => 'WS', :name => 'Samoan Tālā', :code => 'WST', :symbol => 'WS$', :symbol_position => 'before' },
      { :country_id => '203', :country_name => 'San Marino', :country_iso => 'SM', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '208', :country_name => 'Sao Tome and Principe', :country_iso => 'ST', :name => 'São Tomé and Príncipe Dobra', :code => 'STD', :symbol => 'Db', :symbol_position => 'before' },
      { :country_id => '192', :country_name => 'Saudi Arabia', :country_iso => 'SA', :name => 'Saudi Riyal', :code => 'SAR', :symbol => 'ر.س', :symbol_position => 'before' },
      { :country_id => '204', :country_name => 'Senegal', :country_iso => 'SN', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '189', :country_name => 'Serbia', :country_iso => 'RS', :name => 'Serbian Dinar', :code => 'RSD', :symbol => 'din.', :symbol_position => 'before' },
      { :country_id => '194', :country_name => 'Seychelles', :country_iso => 'SC', :name => 'Seychellois Rupee', :code => 'SCR', :symbol => '', :symbol_position => 'before' },
      { :country_id => '202', :country_name => 'Sierra Leone', :country_iso => 'SL', :name => 'Sierra Leonean Leone', :code => 'SLL', :symbol => 'Le', :symbol_position => 'before' },
      { :country_id => '197', :country_name => 'Singapore', :country_iso => 'SG', :name => 'Singapore Dollar', :code => 'SGD', :symbol => 'S$', :symbol_position => 'before' },
      { :country_id => '210', :country_name => 'Sint Maarten (Dutch part)', :country_iso => 'SX', :name => 'Netherlands Antillean Guilder', :code => 'ANG', :symbol => 'NAƒ', :symbol_position => 'before' },
      { :country_id => '201', :country_name => 'Slovakia', :country_iso => 'SK', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '199', :country_name => 'Slovenia', :country_iso => 'SI', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '193', :country_name => 'Solomon Islands', :country_iso => 'SB', :name => 'Solomon Islands Dollar', :code => 'SBD', :symbol => 'SI$', :symbol_position => 'before' },
      { :country_id => '205', :country_name => 'Somalia', :country_iso => 'SO', :name => 'Somali Shilling', :code => 'SOS', :symbol => 'Sh.So.', :symbol_position => 'before' },
      { :country_id => '246', :country_name => 'South Africa', :country_iso => 'ZA', :name => 'South African Rand', :code => 'ZAR', :symbol => 'R', :symbol_position => 'before' },
      { :country_id => '90', :country_name => 'South Georgia and the South Sandwich Islands', :country_iso => 'GS', :name => 'Pound Sterling', :code => 'GBP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '207', :country_name => 'South Sudan', :country_iso => 'SS', :name => 'South Sudanese Pound', :code => 'SSP', :symbol => '', :symbol_position => 'before' },
      { :country_id => '68', :country_name => 'Spain', :country_iso => 'ES', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
      { :country_id => '130', :country_name => 'Sri Lanka', :country_iso => 'LK', :name => 'Sri Lankan Rupee', :code => 'LKR', :symbol => 'රු', :symbol_position => 'before' },
      { :country_id => '195', :country_name => 'Sudan', :country_iso => 'SD', :name => 'Sudanese Pound', :code => 'SDG', :symbol => 'ج.س.', :symbol_position => 'before' },
      { :country_id => '206', :country_name => 'Suriname', :country_iso => 'SR', :name => 'Surinamese Dollar', :code => 'SRD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '200', :country_name => 'Svalbard and Jan Mayen', :country_iso => 'SJ', :name => 'Norwegian Krone', :code => 'NOK', :symbol => 'kr', :symbol_position => 'before' },
      { :country_id => '212', :country_name => 'Swaziland', :country_iso => 'SZ', :name => 'Swazi Lilangeni', :code => 'SZL', :symbol => 'E', :symbol_position => 'before' },
      { :country_id => '196', :country_name => 'Sweden', :country_iso => 'SE', :name => 'Swedish Krona', :code => 'SEK', :symbol => 'kr', :symbol_position => 'before' },
      { :country_id => '43', :country_name => 'Switzerland', :country_iso => 'CH', :name => 'Swiss Franc', :code => 'CHF', :symbol => 'Fr.', :symbol_position => 'before' },
      { :country_id => '211', :country_name => 'Syrian Arab Republic', :country_iso => 'SY', :name => 'Syrian Pound', :code => 'SYP', :symbol => '£S', :symbol_position => 'before' },
      { :country_id => '227', :country_name => 'Taiwan', :country_iso => 'TW', :name => 'Taiwan New Dollar', :code => 'TWD', :symbol => 'NT$', :symbol_position => 'before' },
      { :country_id => '218', :country_name => 'Tajikistan', :country_iso => 'TJ', :name => 'Tajikistani Somoni', :code => 'TJS', :symbol => '', :symbol_position => 'before' },
      { :country_id => '228', :country_name => 'Tanzania, United Republic of', :country_iso => 'TZ', :name => 'Tanzanian Shilling', :code => 'TZS', :symbol => 'TSh', :symbol_position => 'before' },
      { :country_id => '217', :country_name => 'Thailand', :country_iso => 'TH', :name => 'Thai Baht', :code => 'THB', :symbol => '฿', :symbol_position => 'before' },
      { :country_id => '220', :country_name => 'Timor-Leste', :country_iso => 'TL', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '216', :country_name => 'Togo', :country_iso => 'TG', :name => 'West African CFA Franc', :code => 'XOF', :symbol => 'CFA', :symbol_position => 'before' },
      { :country_id => '219', :country_name => 'Tokelau', :country_iso => 'TK', :name => 'New Zealand Dollar', :code => 'NZD', :symbol => 'NZ$', :symbol_position => 'before' },
      { :country_id => '223', :country_name => 'Tonga', :country_iso => 'TO', :name => 'Tongan Paʻanga', :code => 'TOP', :symbol => 'T$', :symbol_position => 'before' },
      { :country_id => '225', :country_name => 'Trinidad and Tobago', :country_iso => 'TT', :name => 'Trinidad and Tobago Dollar', :code => 'TTD', :symbol => 'TT$', :symbol_position => 'before' },
      { :country_id => '222', :country_name => 'Tunisia', :country_iso => 'TN', :name => 'Tunisian Dinar', :code => 'TND', :symbol => 'د.ت', :symbol_position => 'before' },
      { :country_id => '224', :country_name => 'Turkey', :country_iso => 'TR', :name => 'Turkish Lira', :code => 'TRY', :symbol => '₺', :symbol_position => 'before' },
      { :country_id => '221', :country_name => 'Turkmenistan', :country_iso => 'TM', :name => 'Turkmenistan New Manat', :code => 'TMT', :symbol => 'T', :symbol_position => 'before' },
      { :country_id => '213', :country_name => 'Turks and Caicos Islands', :country_iso => 'TC', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '226', :country_name => 'Tuvalu', :country_iso => 'TV', :name => 'Australian Dollar', :code => 'AUD', :symbol => 'A$', :symbol_position => 'before' },
      { :country_id => '230', :country_name => 'Uganda', :country_iso => 'UG', :name => 'Ugandan Shilling', :code => 'UGX', :symbol => 'USh', :symbol_position => 'before' },
      { :country_id => '229', :country_name => 'Ukraine', :country_iso => 'UA', :name => 'Ukrainian Hryvnia', :code => 'UAH', :symbol => '₴', :symbol_position => 'before' },
      { :country_id => '2', :country_name => 'United Arab Emirates', :country_iso => 'AE', :name => 'United Arab Emirates Dirham', :code => 'AED', :symbol => 'د.إ', :symbol_position => 'before' },
      { :country_id => '77', :country_name => 'United Kingdom', :country_iso => 'GB', :name => 'Pound Sterling', :code => 'GBP', :symbol => '£', :symbol_position => 'before' },
      { :country_id => '232', :country_name => 'United States', :country_iso => 'US', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '231', :country_name => 'United States Minor Outlying Islands', :country_iso => 'UM', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '233', :country_name => 'Uruguay', :country_iso => 'UY', :name => 'Uruguayan Peso', :code => 'UYU', :symbol => '$U', :symbol_position => 'before' },
      { :country_id => '234', :country_name => 'Uzbekistan', :country_iso => 'UZ', :name => 'Uzbekistan Som', :code => 'UZS', :symbol => '', :symbol_position => 'before' },
      { :country_id => '241', :country_name => 'Vanuatu', :country_iso => 'VU', :name => 'Vanuatu Vatu', :code => 'VUV', :symbol => 'VT', :symbol_position => 'before' },
      { :country_id => '237', :country_name => 'Venezuela, Bolivarian Republic of', :country_iso => 'VE', :name => 'Venezuelan Bolívar', :code => 'VEF', :symbol => 'Bs.F.', :symbol_position => 'before' },
      { :country_id => '240', :country_name => 'Vietnam', :country_iso => 'VN', :name => 'Vietnamese Dong', :code => 'VND', :symbol => '₫', :symbol_position => 'before' },
      { :country_id => '238', :country_name => "Virgin Islands, British", :country_iso => 'VG', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '239', :country_name => "Virgin Islands, U.S.", :country_iso => 'VI', :name => 'United States Dollar', :code => 'USD', :symbol => '$', :symbol_position => 'before' },
      { :country_id => '242', :country_name => 'Wallis and Futuna', :country_iso => 'WF', :name => 'CFP Franc', :code => 'XPF', :symbol => 'F', :symbol_position => 'before' },
      { :country_id => '66', :country_name => 'Western Sahara', :country_iso => 'EH', :name => 'Moroccan Dirham', :code => 'MAD', :symbol => 'MAD', :symbol_position => 'before' },
      { :country_id => '244', :country_name => 'Yemen', :country_iso => 'YE', :name => 'Yemeni Rial', :code => 'YER', :symbol => '﷼', :symbol_position => 'before' },
      { :country_id => '247', :country_name => 'Zambia', :country_iso => 'ZM', :name => 'Zambian Kwacha', :code => 'ZMW', :symbol => 'ZMW', :symbol_position => 'before' },
      { :country_id => '248', :country_name => 'Zimbabwe', :country_iso => 'ZW', :name => 'Zimbabwe Dollar', :code => 'ZWD', :symbol => 'Z$', :symbol_position => 'before' },
      { :country_id => '15', :country_name => 'Åland Islands', :country_iso => 'AX', :name => 'Euro', :code => 'EUR', :symbol => '€', :symbol_position => 'before' },
  ]

  def up
    ITEMS.each do |item|
      currency = Spree::Currency.find_or_create_by(name: item[:name], code: item[:code], symbol: item[:symbol], symbol_position: item[:symbol_position])
      country = Spree::Country.find(item[:country_id])
      country.currency_id = currency.id
      country.save!
    end
  end

  def down
    Spree::Country.update_all(currency_id: nil)
    Spree::Currency.destroy_all
  end
end
